engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**/*
exclude_paths:
- lib/**/*
- node_modules/**/*
- _test_/**/*
- test/**/*
- templates/**/*
- src/options.js
