---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    exclude_fingerprints:
    - ef24af82473adcd8f2a9d49c1a1e9938
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths: []
